### ISSUE TITLE
How to use chartjs-plugin-gradient

### ISSUE THREAD

**Issue by AmitKumarHQ** [SeanSobey/ChartjsNodeCanvas#102]
Does anyone knows how can I use this inside chartjs-node-canvas

<b>Code:</b> https://srcb.in/GWRaFimOiN

**Comment by SeanSobey** [comment]
Hi there,

Check out how [this lib](https://github.com/SeanSobey/ChartjsNodeCanvas/blob/master/src/index.ts) includes support for [background colour](https://github.com/SeanSobey/ChartjsNodeCanvas/blob/master/src/backgroundColourPlugin.ts). You should be able to use the boilerplate code to do what you need.
