### ISSUE TITLE
Default font does not work on Ubuntu

### ISSUE THREAD

**Issue by Kyzegs** [SeanSobey/ChartjsNodeCanvas#105]
**Describe the bug**
The text does not get displayed on an Ubuntu system. 

Windows:

![image](https://user-images.githubusercontent.com/45851377/169652126-2381adc4-5c27-457b-af2c-39872bd73e97.png)

Ubuntu:

![image](https://user-images.githubusercontent.com/45851377/169652144-cea76447-968c-47cc-98ea-7ce069bdb595.png)

**Versions**
* NodeJS version: v17.8.0
* Chart.JS version: ^3.7.1
* Typescript version (if applicable): ^4.6.3

**Comment by SeanSobey** [comment]
Hi there!

This lib is a small bit of glue between some other libs and as such the issues related to deployment and os support are dependant and resulting from the underlying libs, in this case it looks like [node-canvas](https://github.com/Automattic/node-canvas).

I am mostly a Windows user but do attempt to provide docs and test/CI support for other OS here, and I spent a bit of time adding docker/CI support for [testing on ubuntu](#106). Currently there is some test-related issues preventing the MR (my time is quite limited atm) but the fixes for the [tests for custom fonts](https://github.com/SeanSobey/ChartjsNodeCanvas/pull/106/files#diff-a06dc3fe2ea41fc9d3f683e583c1f7b91f3a010a416ad9f6f797731d09c2260c) look fine visually.

_**There was no required code changes in this lib I suspect you just to install some dependencies on ubuntu, the visuals you provided are consistent with my experience.**_

Have a look at the [docs](https://github.com/SeanSobey/ChartjsNodeCanvas#custom-fonts) (and `node-canvas` docs therein) regarding fonts, environments and my [ubuntu dockerfile](https://github.com/SeanSobey/ChartjsNodeCanvas/pull/106/files#diff-67417c1fcdebaab85de9962b28fa153cfa7f0f585bc9e7f3616c9146541adb7d) for clarity on the dependencies etc on getting custom fonts to work.

Hope this helps!

**Comment by SrS2225a** [comment]
> Hi there!
> 
> This lib is a small bit of glue between some other libs and as such the issues related to deployment and os support are dependant and resulting from the underlying libs, in this case it looks like [node-canvas](https://github.com/Automattic/node-canvas).
> 
> I am mostly a Windows user but do attempt to provide docs and test/CI support for other OS here, and I spent a bit of time adding docker/CI support for [testing on ubuntu](#106). Currently there is some test-related issues preventing the MR (my time is quite limited atm) but the fixes for the [tests for custom fonts](https://github.com/SeanSobey/ChartjsNodeCanvas/pull/106/files#diff-a06dc3fe2ea41fc9d3f683e583c1f7b91f3a010a416ad9f6f797731d09c2260c) look fine visually.
> 
> _**There was no required code changes in this lib I suspect you just to install some dependencies on ubuntu, the visuals you provided are consistent with my experience.**_
> 
> Have a look at the [docs](https://github.com/SeanSobey/ChartjsNodeCanvas#custom-fonts) (and `node-canvas` docs therein) regarding fonts, environments and my [ubuntu dockerfile](https://github.com/SeanSobey/ChartjsNodeCanvas/pull/106/files#diff-67417c1fcdebaab85de9962b28fa153cfa7f0f585bc9e7f3616c9146541adb7d) for clarity on the dependencies etc on getting custom fonts to work.
> 
> Hope this helps!

Yes, that's kind of  whats going on. It's easy enough to fix. All he needs to do is install one to `~/.local/share/fonts/` or simply install a package such as `gnu-free-fonts`, then make the font of his choice his system default. The arch linux docs has a great guide on how to set them up properly, and should work for Ubuntu as well. https://wiki.archlinux.org/title/Fonts

**Comment by Kyzegs** [comment]
I got it working. Thanks for the input on how to solve the issue.
