### ISSUE TITLE
Some problem with memory leak

### ISSUE THREAD

**Issue by baho-dn** [SeanSobey/ChartjsNodeCanvas#11]
Hi, have some problem with memory leak. Is there a garbage disposal method?
after 4 uses. 
![image](https://user-images.githubusercontent.com/44977928/56238956-6e19f080-6098-11e9-834a-907446be3d7f.png)

read requests like this did not see, maybe a problem on my part?

```javascript
const { CanvasRenderService } = require('chartjs-node-canvas');

const chartCallback = (ChartJS) => {
    ChartJS.defaults.global.responsive = true;
    ChartJS.defaults.global.maintainAspectRatio = false; 
};

const CreatorChart = async(config) =>{
        const canvasRenderService = new CanvasRenderService(config.width, config.height, chartCallback);
        const a = await canvasRenderService.renderToDataURL(config) 
        return a.split(",")[1]; 
}

module.exports = CreatorChart
```

**Comment by SeanSobey** [comment]
Hi, yeah I recently addressed some memory leak issues.

Your usage of `ChartjsNodeCanvas` is fine, are you using the latest version (`2.2.4`)?

If yes then maybe you can provide an example of the calling code? I do have some [tests](https://github.com/SeanSobey/ChartjsNodeCanvas/blob/master/src/index.spec.ts#L328) that are supposed to check for this exact case.

**Comment by baho-dn** [comment]
Solved the problem, thanks a lot for a great product.

**Comment by vooit** [comment]
aleksandrov-ivan it would be nice to provide a solution

**Comment by aleksandrov-ivan** [comment]
> aleksandrov-ivan it would be nice to provide a solution

https://github.com/SeanSobey/ChartjsNodeCanvas#Full%20Example
Memory Management

In my case, there are several sizes of graphs and a canvas is created for each separately.
How to delete an object completely, unfortunately I could not find it.
