### ISSUE TITLE
Failed to install on Ubuntu 22.04 (WSL2)

### ISSUE THREAD

**Issue by AmitKumarHQ** [SeanSobey/ChartjsNodeCanvas#114]
## Issue
So today I tried to install chart.js and chartjs-node-canvas but it gave me this error.
![image](https://user-images.githubusercontent.com/94821119/182020440-ba4f1bd0-57e4-4305-bdf7-023191929571.png)
Can anyone please help me out..?

Full error: https://srcb.in/3rpPtaXLEi

## Tested on
- [Node.js](https://nodejs.org/) - v18.5.0
- [npm](https://npmjs.com/) - v8.12.1
- [chart.js](https://npmjs.com/package/chart.js) - v3.8.2

**Comment by bluemanos** [comment]
Similar issue: https://github.com/Automattic/node-canvas/issues/2052

Solution: use node 17
