### ISSUE TITLE
Registered font does not load

### ISSUE THREAD

**Issue by CastleArg** [SeanSobey/ChartjsNodeCanvas#13]
I'm using this in a JavaScript azure function which has no system fonts.
I got a ttf file from Google fonts and am trying to register exactly as in the docs.
However I'm getting an 'all fallbacks failed' error and the chart labels are coming out as little squares.

**Comment by SeanSobey** [comment]
Hmm, yeah fonts are quite a tricky thing historically.

I am investigating some issues I have found, but have not replicated your exact issue. I think I have fixed what might be your issue anyway (specifically the separate instance that the font callback runs in from the canvas instance of node-canvas, see https://github.com/SeanSobey/ChartjsNodeCanvas/blob/master/src/index.ts#L36), but I do think fonts may not work as expected.

I will have a fixed version out shortly (away for a few days) that you can try but do suspect there may be more issues.

In the meantime, this lib just delegates to the [node-canvas](https://github.com/Automattic/node-canvas#registerfont) API, so I suggest having a look at that first and make sure you are following all the caveats.

**Comment by SeanSobey** [comment]
In case you are still looking at this issue you can try the latest version ([2.4.1](https://github.com/SeanSobey/ChartjsNodeCanvas/releases/tag/2.4.1)) to rty resolve your issue.

**Comment by Taaqif** [comment]
Experiencing this same issue on version 3.0.6. 
Not too sure what we're doing wrong here as we register the font prior to loading the chart however the following Error occurs: 
`(process:9160): Pango-WARNING **: 01:29:51.670: couldn't load font "Myriad Pro Not-Rotated 14px", falling back to "Sans Not-Rotated 14px", expect ugly output.`

Azure function apps seems to not have any standard fonts available so loading an external font is the only means. 
We have also ensured the file does exist and is being loaded correctly but still no luck

**Comment by niyeronsin** [comment]
@Taaqif Were you able to resolve the issue?
