### ISSUE TITLE
CanvasRenderService not working when deployed in a server but yes in localhost

### ISSUE THREAD

**Issue by caminosajalberto** [SeanSobey/ChartjsNodeCanvas#15]
The server responds with a 500 error code. Other petitions works perfectly. I did some tests and the problem is in this line:
const canvasRenderService = new CanvasRenderService(width, height, (ChartJS) => { });
but i dont know why. Could you help me? Is needed something more than only the npm packgages? 

I'm using an express app with node.js, and in localhost it works great. The server is a web app in Azure.

Thanks in advance.

**Comment by SeanSobey** [comment]
Hi, sorry for the delayed response.

Sure I can try to assist. What error are you getting?

Gut feel says it is most likely an issue with [node-canvas](https://github.com/Automattic/node-canvas), 
It requires compilation of a native binary.

I would check your `npm install` logs on your Azure box, what OS is that running on?
Check out the [compiling](https://github.com/Automattic/node-canvas#compiling) docs too

**Comment by caminosajalberto** [comment]
Hi Sean,

Now it is solved. The problem was with the canvas library and fonts, so now it works great. 

Thank you for your answer and great work!

**Comment by SurgicalCrow** [comment]
I am facing same problem now
