### ISSUE TITLE
Show yValue in canvas.

### ISSUE THREAD

**Issue by visibleajay** [SeanSobey/ChartjsNodeCanvas#17]
Thank you making a library to render **Awesome** & **fast** Charts on Canvas in node. Thank you so much!.

We have a functionality in which we would like to add y value for each chart (bar or pie) in the generated chart. We had used generateLabels and afterDatasetsDraw (chartJS lifecycle) to make the same change on our chart.

Sample Code for Reference
```
generateLabels: function(chart) {
  const data = chart.data;
  if ( data.labels.length && data.datasets.length ) {
      return data.labels.map(function (label, index) {
        var meta = chart.getDatasetMeta(0);
        if (!meta.hidden) {
          const ctx  = chart.chart.ctx;
          meta.data.forEach(function(element, index) {
              ctx.fillStyle = 'rgba(0, 0, 0, 0.5)';
              ctx.textAlign = 'center';
              ctx.textBaseline = 'middle';
                  
              var model = element._model;
              console.log(element._yScale);
              var scaleMax = element._yScale.maxHeight;
              var yPos = (scaleMax - model.y) / scaleMax >= 0.93 ? model.y + 10 : model.y - 5;

              ctx.fillText(label, model.x, yPos);
          });
        }
      });
  }
}
```

With the above code, we are receiving '_yScale' as undefined as I believe the dynamic _yScale is unavailable while rendering. 

If possible, Would like to know a way in which we could add a yValue to our server side charts.  Please let us know if any more information is needed.

Looking forward to your response.
Thank you for giving your time.

**Comment by SeanSobey** [comment]
Hi,
This library (Chart JS Node Canvas) only facilitates running ChartJS on an emulated canvas using node and does not actually involve anything related to the Chart JS library itself, for example writing plugins, which it appears you are wanting to do.

I would suggest having a look at the [official plugin directory](https://www.chartjs.org/docs/2.7.2/notes/extensions.html) for examples of plugins and how they work, and maybe even one of them is doing what you want? Like [chartjs-plugin-datalabels](https://chartjs-plugin-datalabels.netlify.com/) ([example(https://chartjs-plugin-datalabels.netlify.com/samples/charts/bar.html), and [samples](https://chartjs-plugin-datalabels.netlify.com/samples/index.html)?). If that does not work I would suggest looking at the [chart.js source code](https://github.com/chartjs/Chart.js), like [core.controller.js](https://github.com/chartjs/Chart.js/blob/master/src/core/core.controller.js). The code is in an old style but logically laid out.

Good luck!

It's quite unlikely but possible that some missing feature of Canvas library is causing your issue, so in the case that you can run your code fine in a browser, but not via this library then we can repoen the issue and investigate.

**Comment by visibleajay** [comment]
Hey Sean,

Thank you for your response.

For bar graph to show labels,
```
                            const model = element._model;
                            const { x, y, base } = model;

                            ctx.fillText(dataString, x, y - 5);
```

For pie graph, we are using startAngle, endAngle & radius to show the labels.

Thank you for the acknowledgement.
