### ISSUE TITLE
Any hints on adding locally build chartjs to chartjs-node-canvas.

### ISSUE THREAD

**Issue by visibleajay** [SeanSobey/ChartjsNodeCanvas#21]
Repo := https://github.com/bevingtongroup/Chart.js for ChartJs.

**Comment by SeanSobey** [comment]
Hi,

I am not quite sure what your question is. Are you asking how to [npm install](https://docs.npmjs.com/cli/install) a local foder?
```
npm install <folder>
```
or a forked gihub repo?
```
npm install https://github.com/bevingtongroup/Chart.js
```
None of these have anything to do with this package

**Comment by visibleajay** [comment]
Apologies for giving only a short intro of what we were looking for.

We would like to use https://github.com/bevingtongroup/Chart.js as a ChartJS dependency for chartjs-node-canvas library. To develop the prod, we builded the repo and copied the bundled files to node_modules/Chart.Js. 

Before releasing it to prod, we would like to make it work through an established way.

Had added "bevingtongroup/Chart.js" : "*", "./lib/chartjs/Chart.js" in package.json but was unable to load the Chart.js with both way.

Please let me know if I missed anything here.

**Comment by visibleajay** [comment]
Created a different lib folder with dist of both the projects (ChartJS & chartjs-node-canvas) and used "./lib/chartjs-node-canvas/dist" to refer the CanvasRenderService var.

**Comment by SeanSobey** [comment]
Ah ok, its sound like you are wanting to use your own version of chart.js, eg your `https://github.com/bevingtongroup/Chart.js`.

You have some options:

1. Use a private npm repository

Like [this](https://medium.com/engenharia-noalvo/ways-to-have-your-private-npm-registry-and-a-final-diy-solution-eed001a88e74), or the newer [GitHub one](https://github.com/features/package-registry).

You then need to [configure](https://docs.npmjs.com/misc/registry) your local and CI build pipe;lines to use that registry.

If I were doing this in a production app this is the prefered approach.

2. Install from github

As I mentioned before you can reference an npm module [from a github repo directly](https://stackoverflow.com/questions/17509669/how-to-install-an-npm-package-from-github-directly). Eg:

```
npm i chartjs-node-canvas
```

```
npm i bevingtongroup/Chart.js
```
Your app now uses your version of ChartJS. This is quicker and easier than the above option but not ideal for a production app.

3. Include your chart JS directly.

Include the contents of `https://github.com/bevingtongroup/Chart.js/src` in eg `/Chart.js/src/`

Use a chart factory function for `chartjs-node-canvas`:

```js
const { CanvasRenderService } = require('chartjs-node-canvas');

const chartJsFactory = () => {
	const chartJS = require('./Chart.js/src/chart');
	return chartJS;
};

(async () => {
	const width = 400; //px
	const height = 400; //px
	const configuration = {
        ... // See https://www.chartjs.org/docs/latest/configuration
	};
	const canvasRenderService = new CanvasRenderService(width, height, undefined, undefined, chartJsFactory);
	const image = await canvasRenderService.renderToBuffer(configuration);
	const dataUrl = await canvasRenderService.renderToDataURL(configuration);
	const stream = canvasRenderService.renderToStream(configuration);

	...
})();
```

This is similar to what you have done, except the local copy of `chartjs-node-canvas` is not necessary. This would generally be the least preferred approach.
