### ISSUE TITLE
Support for devicePixelRatio

### ISSUE THREAD

**Issue by kochis** [SeanSobey/ChartjsNodeCanvas#22]
Is there any way with this library to set `devicePixelRatio` when drawing to canvas?

chartjs-node exposes this as a top-level argument to the constructor: https://github.com/vmpowerio/chartjs-node/commit/6dabecfc4fce0d7fc858eea0aeb3b4ded7c8bdee

**Comment by SeanSobey** [comment]
Hi there,

`devicePixelRatio` is an [option](https://www.chartjs.org/docs/latest/general/device-pixel-ratio.html), so you should be able to set it easily:

```js
const { CanvasRenderService } = require('chartjs-node-canvas');

(async () => {
	const width = 400;
	const height = 400;
	const canvasRenderService = new CanvasRenderService(width, height, (ChartJS) => {
                // Globally
		ChartJS.defaults.global.devicePixelRatio = 2;
	});
        // Per chart
	const configuration = {
		options: {
			devicePixelRatio: 2
		}
	}
    const canvasRenderService = new CanvasRenderService(width, height, chartCallback);
    const image = await canvasRenderService.renderToBuffer(configuration);
})();
```

**Comment by kochis** [comment]
Worked like a charm, thanks!
