### ISSUE TITLE
Fontconfig error: Cannot load default config file

### ISSUE THREAD

**Issue by mathiswi** [SeanSobey/ChartjsNodeCanvas#27]
Hey, 
I'm using this library in an serverless enviroment to generate charts in pdf reports which works great when I run it locally with serverless-offline.
When ran on AWS though I always get the error "Fontconfig error: Cannot load default config file" and the chart renders with a broken font (see picture).
To generate the pdf I use handlebars with puppeteer which is working without any problems.

Any idea how to fix this on my end? 

![Screenshot_20200107_105807](https://user-images.githubusercontent.com/39401715/71886671-e8b20100-313c-11ea-9ff8-d165308a5dac.png)

**Comment by mathiswi** [comment]
Actually after hours of trying everything before opening the issue I just found a solution.

I just tried creating the canvas after the headless chromium for creating the pdf is launched and that seemed to have fixed the font issue I was having.

**Comment by SeanSobey** [comment]
Hi,

Yes font related errors have always been quite tricky with canvas. Thanks for posting your resolution!
