### ISSUE TITLE
Non-english support on label option

### ISSUE THREAD

**Issue by thuraucsy** [SeanSobey/ChartjsNodeCanvas#3]
Thanks for the nice library. I'm starting to use the library in lambda and when setting Japanese language, for example.

`labels: ["1日","2日","3日","4日","5日","6日","7日","8日","9日","10日","11日","12日","13日","14日","15日","16日","17日","18日","19日","20日","21日","22日","23日","24日","25日","26日","27日","28日","29日","30日","31日"],`

the result is

![chartjs-hor](https://user-images.githubusercontent.com/9957531/49428937-a35d2a80-f7ea-11e8-8ba6-713ba97b1ad6.png)

**Is there any work around to fix it?**

**Comment by thuraucsy** [comment]
I'm using **chartjs-node-canvas@1.1.6** (latest version) and since not supporting non-english **canvas-prebuilt.registerFont()** yet, I'm writing directly into _/dist/index.js_ at line 44 like that

```
renderChart(configuration) {
 if (configuration && configuration.data && configuration.data.font && configuration.data.font.file && 
  configuration.data.font.fontFace) {
            canvas_prebuilt_1.registerFont(configuration.data.font.file, configuration.data.font.fontFace);
 }
 ....
 ....
```

and then using that from configuration.data

```
   const configuration = {
    type: 'bar',
    data: {
      labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
      datasets: [{
        label: '# of Votes',
        data: [12, 19, 3, 5, 2, 3],
        backgroundColor: [
        'rgba(255, 99, 132, 0.2)',
        'rgba(54, 162, 235, 0.2)',
        'rgba(255, 206, 86, 0.2)',
        'rgba(75, 192, 192, 0.2)',
        'rgba(153, 102, 255, 0.2)',
        'rgba(255, 159, 64, 0.2)'
        ],
        borderColor: [
        'rgba(255,99,132,1)',
        'rgba(54, 162, 235, 1)',
        'rgba(255, 206, 86, 1)',
        'rgba(75, 192, 192, 1)',
        'rgba(153, 102, 255, 1)',
        'rgba(255, 159, 64, 1)'
        ],
        borderWidth: 1
      }],
      font: {
        file: "./komorebi-gothic.ttf",
        fontFace: {
          family: "木漏れ日ゴシック"
        }
      }
    }
  };
```

just add the font file where the configuration source file exists. It works now!
Hope that function support in the next release. Thanks!

![chartjs-hor3](https://user-images.githubusercontent.com/9957531/49485347-fcc26980-f87d-11e8-9b73-ed683015a3a5.png)

**Comment by SeanSobey** [comment]
You can just do a call to `canvas_prebuilt` in your calling code before you do the render:
```js
const canvas_prebuilt = require("canvas-prebuilt");
const { CanvasRenderService } = require('chartjs-node-canvas');

(async () => {
    const canvasRenderService = new CanvasRenderService(width, height, chartCallback);
	canvas_prebuilt.registerFont(fontFile, fontFace);
	
    const image = await canvasRenderService.renderToBuffer(configuration);
    const dataUrl = await canvasRenderService.renderToDataURL(configuration);
    const stream = canvasRenderService.renderToStream(configuration);
})();
```

**Comment by neo125874** [comment]
@thuraucsy @SeanSobey Hi both, I tried the method above but not working, 
any detail could you share more?

`const canvas_prebuilt = require("canvas-prebuilt");`
`const fontFile = "./font/HDZB_27.TTF"`
`const fontFace = {
  family: "HDZB_27"
};`
`canvas_prebuilt.registerFont(fontFile, fontFace);`

but the chinese still not showing, thanks!

**Comment by thuraucsy** [comment]
In the latest version [(/dist/index.js),](https://github.com/SeanSobey/ChartjsNodeCanvas/blob/master/dist/index.js)
**require("canvas-prebuilt");** was changing to **require("canvas");**

Please change and test that first.

If it doesn't work, try my way by touching directly to /node_modules/chartjs-node-canvas/dist/index.js although it is not a recommended way.

https://github.com/SeanSobey/ChartjsNodeCanvas/issues/3#issuecomment-444332054

**Comment by SeanSobey** [comment]
Yes, thanks @thuraucsy that is correct. Since this is not the first issue with fonts I have added font support directly on this lib (v2.4.0), see the [Usage](https://github.com/SeanSobey/ChartjsNodeCanvas#custom-fonts), and example [test(https://github.com/SeanSobey/ChartjsNodeCanvas/blob/master/src/index.e2e.spec.ts#L246).
