### ISSUE TITLE
Problem with labels on ChartJs rendering since v2.4.1

### ISSUE THREAD

**Issue by Kahr-Noss** [SeanSobey/ChartjsNodeCanvas#30]
Hello I'm using your package to add ChartJs graphs to PDF reports.

I noticed today that after reinstalling the node packages, there was an unusual spacing between letters in labels on the graphs. (see below)
BEFORE:
<img width="460" alt="Screen Shot 2020-01-31 at 17 40 56" src="https://user-images.githubusercontent.com/28529737/73524831-46422080-4451-11ea-8c2f-260940aacfd9.png">
AFTER:
<img width="498" alt="Screen Shot 2020-01-31 at 17 39 47" src="https://user-images.githubusercontent.com/28529737/73524860-55c16980-4451-11ea-845a-27c346500200.png">

Since my code didn't change, I checked your module and saw that you released an update (v2.4.1) that requires canvas v2.6.1.

After rolling back to ChartjsNodeCanvas to v2.4.0 and canvas to v2.6.0 my problem was solved.

I didn't check what are the new features of this more recent version of canvas, but I wanted to let you know that it could broke some existing applications, so maybe you should change the version number to a "minor release" instead of a "patch release".

Anyway, thank you for your package.

**Comment by SeanSobey** [comment]
Hi! Thanks for reporting this issue!

When updating this package version I follow a usual protocol of checking changelogs of dependencies and running integration tests to make sure things work the same. I have [integration tests](https://github.com/SeanSobey/ChartjsNodeCanvas/blob/master/src/index.e2e.spec.ts#L77) that should cover situations as you describe, so maybe I have missed something. Do you have a public repo or maybe some code I can use to replicate this?

Its does sound like a potential bug with `node-canvas` but in my experience fonts do have a tendency to do strange things, especially across platforms and in different environments. If so I can post an issue on node-canvas and help others avoid this, but I would just like to be sure before I deprecate the npm package and roll back.
