### ISSUE TITLE
Is SVG Type supported for renderToStream

### ISSUE THREAD

**Issue by dills122** [SeanSobey/ChartjsNodeCanvas#31]
I was trying to use this to render the charts to SVGs images, but when I try to include the mime/type `image/svg+xml` it gives me a this error:

```
throw new Error(`Un-handled mimeType: ${mimeType}`);
                ^
Error: Un-handled mimeType: image/svg+xml
    at CanvasRenderService.renderToStream (/servicing-sdk/node_modules/chartjs-node-canvas/dist/index.js:129:23)
```

which looks to be due to it not being available in the switch statement in this function.

https://github.com/SeanSobey/ChartjsNodeCanvas/blob/40223d65ab3812d72728e1b762b7ecea034e5118/src/index.ts#L148

Am I just missing something?

Here's the code I was trying this with

```javascript
    const { CanvasRenderService } = dependencies.chartJS;
    const { height, width } = constants.medium;
    let renderService = new CanvasRenderService(width, height, (ChartJS) => { }, 'SVG');
let stream = await renderService.renderToStream({
        //Example Chartjs object
    }, 'image/svg+xml');
```

I tried just using `renderToBuffer` and when I try to specify the same mime type to that method it just doesn't render anything and if omit it then it just renders to the default `PNG` type.

**Comment by dills122** [comment]
After debugging a bit more it looks like the place it is failing/not returning is 
when it calls `toBuffer()` on the canvas.

https://github.com/SeanSobey/ChartjsNodeCanvas/blob/40223d65ab3812d72728e1b762b7ecea034e5118/dist/index.js#L81

If I put any logs after that call in my code or the libs it doesn't print out.

Here is an example I was using to test this.

```javascript
let { Buffer } = require("buffer");

const dependencies = {
    chartJS: require("chartjs-node-canvas")
};

const constants = {
    TYPES: ['PNG', 'SVG'],
    smalll: {
        height: 400,
        width: 400
    },
    medium: {
        height: 500,
        width: 500
    }
};

(async () => {
    console.log("Creating Chart Object");
    const { CanvasRenderService } = dependencies.chartJS;
    const { height, width } = constants.medium;
    let renderService = new CanvasRenderService(width, height, (ChartJS) => {
        ChartJS.defaults.global.animation = false;
        ChartJS.defaults.global.responsive = false;
    }, 'SVG'); //Tried SVG and svg
    try {
        let buffer = await renderService.renderToBuffer({
            type: 'bar',
            data: {
                labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
                datasets: [{
                    label: '# of Votes',
                    data: [12, 19, 3, 5, 2, 3],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        }
                    }]
                }
            }
        }, 'image/svg+xml');
        //When I run this I dont get anthing below this to print out
        console.log("Finished");
        console.log(buffer);
        let base64Str = Buffer.from(buffer).toString("base64");
        console.log(base64Str);
    } catch (e) {
        console.log(e);
    }
})();
```

**Comment by SeanSobey** [comment]
Hi

So this seems to be some unfinished work on my part. I have some tests covering these mime types, but they were excluded. Rerunning them I got the same behaviour you describe. Looking at the [canvas docs](https://github.com/Automattic/node-canvas#canvastobuffer) I noticed them exclusively using the sync API. Switching the tests to just those seems to have fixed the issue, although not quite sure why this is.

I have pushed up `3.0.0` with this API change (switch your code to use `renderToBufferSync`), and note that you may need to install [Image Magik](https://imagemagick.org/script/download.php) for SVG support.

**Comment by dills122** [comment]
First thanks for the repo and making it super easy to use!

Just got to testing your updates and everything is working on my end now.

Thanks for the help and quick resolution.
