### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by paulopelaez** [SeanSobey/ChartjsNodeCanvas#32]
I can generate the image and put it in my pdf normally, but it is of very low quality, as below:

![image](https://user-images.githubusercontent.com/13918656/74335437-fd586900-4d7a-11ea-8a67-9f3207c5b7cf.png)

the impression is that it is all blurred, how can it improve? I greatly appreciate your help.

`const { CanvasRenderService } = require('chartjs-node-canvas');

bellow my code : 

module.exports = app => {

    // See https://www.chartjs.org/docs/latest/configuration

    async function barChart(arrayData) {
        const width = 300 //px
        const height = 300 //px
        const configuration = {
            type: 'bar',
            data: {
                labels: ['Red', 'Blue', 'Yellow', 'Green'],
                datasets: [{
                    label: 'Resultado DISC',
                    data: [12, 19, 3, 5],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                    ],
                    borderColor: [
                        'rgba(255,99,132,1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                    ],
                    borderWidth: 2
                }],
                labels:['D','I','S','C']
            },
            options: {
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero:true
                        }
                    }]
                },
                legend: {
                    labels: {
                        fontColor: 'black',
                    }
                },
            }
        }
        const canvasRenderService = new CanvasRenderService(width, height, (ChartJS) => {
            //console.log('callback entrou')
            ChartJS.defaults.global.elements.rectangle.borderWidth = 2;
        })
        const image = await canvasRenderService.renderToBuffer(configuration)
        //const stream = canvasRenderService.renderToStream(configuration);
        const dataUrl = await canvasRenderService.renderToDataURL(configuration)
        
        return dataUrl
    }
    return { barChart }
}`

**Comment by SeanSobey** [comment]
Increase the size of the canvas for a higher quality image:
```js
const width = 600 //px
const height = 600 //px
```

Also be sure to handle your [memory management](https://github.com/SeanSobey/ChartjsNodeCanvas#memory-management) correctly:
```js
const { CanvasRenderService } = require('chartjs-node-canvas')

const width = 600 //px
const height = 600 //px
const canvasRenderService = new CanvasRenderService(width, height, (ChartJS) => {
	//console.log('callback entrou')
	ChartJS.defaults.global.elements.rectangle.borderWidth = 2;
})

async function barChart(arrayData) {
	...
}

module.exports = app => { return { barChart } }
```
