### ISSUE TITLE
How to get the canvas context?

### ISSUE THREAD

**Issue by marcopiraccini** [SeanSobey/ChartjsNodeCanvas#35]
This is more a question than an issue. 
I would like to access  `canvas` or canvas `context` directly (I need to call `createLinearGradient`)
What is the proper way, if possible?

**Comment by l-portet** [comment]
I was in the same case so I wrote a plugin with `ChartJS.plugins.register` to access the context.

It should look like this:
```javascript
  ChartJS.plugins.register({
    beforeDatasetsDraw: (chart, options) => {
      const ctx = chart.ctx;

      let gradient = ctx.createLinearGradient(0, 0, 0, 450);

      gradient.addColorStop(0, 'rgba(255, 0,0, 0.5)');
      gradient.addColorStop(0.5, 'rgba(255, 0, 0, 0.25)');
      gradient.addColorStop(1, 'rgba(255, 0, 0, 0)');

      chart.data.datasets[0].backgroundColor = gradient;
    }
  });
```

**Comment by SeanSobey** [comment]
👍 Yes, a plugin is the correct solution

**Comment by marcopiraccini** [comment]
It works, indeed :). Tnx
