### ISSUE TITLE
How to use 'datalabels' plugins?

### ISSUE THREAD

**Issue by snowy1000** [SeanSobey/ChartjsNodeCanvas#37]
I want to register 'datalabels' plugin and use it on my chart canvas, but I couldn't figure out how to do so. Can you help me about registering and implementating plugins on my chart?

**Comment by SeanSobey** [comment]
Hi there!

Please see the [plugin section](https://github.com/SeanSobey/ChartjsNodeCanvas#loading-plugins).

Looking at the [datalabels code](https://unpkg.com/chartjs-plugin-datalabels@0.7.0/dist/chartjs-plugin-datalabels.js) the first option should work:
```js
const canvasRenderService = new CanvasRenderService(width, height, (ChartJS) => {
    global.Chart = ChartJS;
    require('chartjs-plugin-datalabels');
    delete global.Chart;
});
```

Actually using the plugin is all the same as ChartJS in the browser.

**Comment by simonbrunel** [comment]
Hi @snowy1000 and @SeanSobey!

`chartjs-plugin-datalabels` provides UMD builds so when it's imported as node module, it doesn't use `global.Chart`. Instead, you need to use the following method:

```js
const chartJsFactory = () => {
    const Chart = require('chart.js');
    require('chartjs-plugin-datalabels');
    delete require.cache[require.resolve('chart.js')];
    delete require.cache[require.resolve('chartjs-plugin-datalabels')];
    return Chart;
}

// ...

const canvasRenderService = new CanvasRenderService(
  chartWidth,
  chartHeight,
  undefined,
  undefined,
  chartJsFactory
);
```

**Comment by justinpincar** [comment]
Hi, I've been running into this same issue as well. When I use either of the two methods above, no error is thrown, but the plugin doesn't take effect. My code is identical to the examples.

If I use the `freshRequire` approach, I get a `TypeError: Cannot read property 'x' of null` in `function orient(point, origin):155` 

Any idea what could be the issue, or any other ideas? Rendering data labels is crucial to my project so if there's another way I'm all ears.

```
    "chart.js": "^2.9.3",
    "chartjs-node-canvas": "^2.4.2",
    "chartjs-plugin-datalabels": "^0.7.0",
```

<img width="1552" alt="Screen Shot 2020-05-25 at 00 37 07" src="https://user-images.githubusercontent.com/810323/82790028-32676380-9e20-11ea-90fa-0775a627d2db.png">

**Comment by justinpincar** [comment]
Doh, figured out my issue. Using the `chartJsFactory` approach did work. Nothing was displaying in my case because I was missing the `options.plugins.datalabels` config entry. I'd wrongly assumed that was only for customization, but it seems it's required.

Thank you very much!
