### ISSUE TITLE
TypeError: Cannot read property '$chartjs' of null

### ISSUE THREAD

**Issue by Selid** [SeanSobey/ChartjsNodeCanvas#38]
Okay so I can't get it to work. I've try to draw a line chart and got it. So I took the example and put it in my code as it but no better. The error I get is 

> `TypeError: Cannot read property '$chartjs' of null

    at injectCSS (node_modules\chart.js\dist\Chart.js:7692:24)
    at Object._ensureLoaded (node_modules\chart.js\dist\Chart.js:7732:4)
    at Object.acquireContext (node_modules\chart.js\dist\Chart.js:7764:9)
    at Chart.construct (node_modules\chart.js\dist\Chart.js:9307:26)
    at new Chart (node_modules\chart.js\dist\Chart.js:9294:7)
    at CanvasRenderService.renderChart (node_modules\chartjs-node-canvas\dist\index.js:151:16)
    at CanvasRenderService.renderToBuffer (node_modules\chartjs-node-canvas\dist\index.js:75:28)`
The "$chartjs" element is used in this method for rootNode. When I log the context passed chartJS, i get 
`CanvasRenderingContext2D { canvas: [Canvas 400x400] }`

The implementation is : 
```
const { CanvasRenderService } = require('chartjs-node-canvas');
const mkdirp = require('mkdirp')
const fs = require('fs');
const util = require('util');
const readFile = util.promisify(fs.readFile);
const writeFile = util.promisify(fs.writeFile);

const width = 400;
const height = 400;
const canvasRenderService = new CanvasRenderService(width, height, chartCallback);
const buildChart = async (values, savePath) => {
 const configuration = {
      type: 'bar',
      data: {
          labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
          datasets: [{
              label: '# of Votes',
              data: [12, 19, 3, 5, 2, 3],
              backgroundColor: [
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(54, 162, 235, 0.2)',
                  'rgba(255, 206, 86, 0.2)',
                  'rgba(75, 192, 192, 0.2)',
                  'rgba(153, 102, 255, 0.2)',
                  'rgba(255, 159, 64, 0.2)'
              ],
              borderColor: [
                  'rgba(255,99,132,1)',
                  'rgba(54, 162, 235, 1)',
                  'rgba(255, 206, 86, 1)',
                  'rgba(75, 192, 192, 1)',
                  'rgba(153, 102, 255, 1)',
                  'rgba(255, 159, 64, 1)'
              ],
              borderWidth: 1
          }]
      },
      options: {
          scales: {
              yAxes: [{
                  ticks: {
                      beginAtZero: true,
                      callback: (value) => '$' + value
                  }
              }]
          }
      }
  };
  const image = await canvasRenderService.renderToBuffer(configuration);
  await mkdirp(savePath.slice(0, savePath.lastIndexOf("/")));
  await writeFile(savePath, image)
}
```
I'm on windows, Node 14.0.0, canvas 2.6.1, chart.js 2.9.3, chartjs-node-canvas 3.0.6
Does someone as a clue ?

**Comment by snowy1000** [comment]
Sorry for answering late.
I recommned you to use the example in the docs.

**Comment by SeanSobey** [comment]
Yeah it looks like something strange is going on, Chart.js is using `dom_platform`, meant for the browser environment, which is only active then this is true:
```
typeof window !== 'undefined' && typeof document !== 'undefined
```
Do you have a repo to replicate the issuse I can look at?

**Comment by SeanSobey** [comment]
Please reopen this if you are still experiencing the issue
