### ISSUE TITLE
Text not being rendered on AWS Lambda

### ISSUE THREAD

**Issue by jskafiAltruist** [SeanSobey/ChartjsNodeCanvas#39]
Hello,

Thank you for creating this awesome library.
I've run into a weird issue where text in my chart is not being parsed when I run my code on AWS Lambda. It runs just fine locally on MacOS Catalina.
This is what I get:
<img width="696" alt="Screen Shot 2020-05-19 at 2 13 21 AM" src="https://user-images.githubusercontent.com/49451133/82308644-ee371780-9976-11ea-9809-d8d42bd1ff64.png">

So far I have attempted:
- rendering the chart as a buffer, as a stream and as a data URL.
- using jpeg file types and png file types.
- removing any fonts that I have imported.

Any help at all is greatly appreciated! 

I'm still attempting to find the root cause of the issue and will update this post if I come to a solution.

**Comment by SeanSobey** [comment]
Hi

This looks like missing dependencies for `canvas`, probably `fontconfig`. I suggest looking at the AWS install instructions for [canvas](https://github.com/Automattic/node-canvas/wiki/Installation%3A-AWS-Lambda) and maybe my [dockerfile](https://github.com/SeanSobey/ChartjsNodeCanvas/blob/master/docker/base/Dockerfile).

**Comment by jskafiAltruist** [comment]
That was the issue. I managed to fix it by doing the following: 
1- adding a `font.conf` file to the root directory with the following:
`<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <dir>./fonts</dir>
  <cachedir>/tmp/fonts-cache</cachedir>
  <config></config>
</fontconfig>`
2- add a `fonts` folder in my root directory which contains the font files
3- use `canvasRenderService.registerFont` and point it to the font file in the root directory.

Thanks @SeanSobey for the suggestion (and for creating this amazing library).

**Comment by siboulet** [comment]
In case that's useful to someone, here is how we got text rendering working in AWS Lambda. We are bundling the necessary font files in our Lambda bundle, and then the only thing we need to do: 

```js
    const chart = new ChartJs(180, 100);
    ...
    chart.registerFont('./fontfile.ttf', { family: 'Font Name' });
```

Then in your chart just use `fontFamily: 'Font Name'.

No messing with fontconfig or font.conf.

**Comment by FelipePardim** [comment]
This information might be useful for those using ChartJSNodeCanvas directly. You can incorporate custom fonts like so:
`import { ChartJSNodeCanvas } from 'chartjs-node-canvas';
// ...
chartJSNodeCanvas.registerFont('./fonts/OpenSans-Regular.ttf', {
  family: 'open sans',
});`
Don't forget to create a **fonts** folder to manage your **.ttf** files, as said above.
