### ISSUE TITLE
Scatter Chart support

### ISSUE THREAD

**Issue by thuraucsy** [SeanSobey/ChartjsNodeCanvas#4]
https://github.com/chartjs/Chart.js/blob/master/samples/charts/scatter/basic.html

**Comment by SeanSobey** [comment]
`const { CanvasRenderService } = require('chartjs-node-canvas');

const width = 400;
const height = 400;
const configuration = {
	type: 'scatter',
	data: {
		datasets: [{
			label: 'Scatter Dataset',
			data: [{
				x: -10,
				y: 0
			}, {
				x: 0,
				y: 10
			}, {
				x: 10,
				y: 5
			}]
		}]
	},
	options: {
		scales: {
			xAxes: [{
				type: 'linear',
				position: 'bottom'
			}]
		}
	}
};

(async () => {
    const canvasRenderService = new CanvasRenderService(width, height);
    const image = await canvasRenderService.renderToBuffer(configuration);
    const dataUrl = await canvasRenderService.renderToDataURL(configuration);
    const stream = canvasRenderService.renderToStream(configuration);
})();`
