### ISSUE TITLE
Loading candlestick from chartjs-chart-financial

### ISSUE THREAD

**Issue by taitems** [SeanSobey/ChartjsNodeCanvas#40]
Hi there,

I'm more familiar with plugins, any idea how to load in this (relatively new) candlestick chart given its also not on npm?

https://github.com/chartjs/chartjs-chart-financial

```
    globalOpts.elements.financial = {
                                  
TypeError: Cannot set property 'financial' of undefined
```

Cheers.

**Comment by taitems** [comment]
Argh of course the moment I finally create an issue I solve it.

They recently updated to support ChartJS 3.0.0 alpha and it was not compatible.

**Comment by vzhilov** [comment]
I have the same issue. So what do we do to ro roll back? Is that ChartJS-Financial problem?

I do:

    Git clone https://github.com/chartjs/chartjs-chart-financial/
    cd chartjs-chart-financial
    npm install
    gulp build

As result I get a file in /dist directory and copy it to me NodeJS project folder.

In my NodeJS app I do:

    const Chart = require(‘chart.js’)
    const ChartFinancial = require(‘./chartjs-chart-financial.js’)

    const chartJsFactory = () => {
        const Chart = require('chart.js');
        require('chartjs-plugin-datalabels');
        require('./chartjs-chart-financial.js');
        delete require.cache[require.resolve('chart.js')];
        delete require.cache[require.resolve('chartjs-plugin-datalabels')];
        delete require.cache[require.resolve('./chartjs-chart-financial.js')];
        return Chart;
    }

    const canvasRenderService = new CanvasRenderService(width, height, chartCallback, undefined, chartJsFactory);


When I run the app I get:

    chartjs-chart-financial.js:227
    globalOpts.elements.financial = {
    TypeError: Cannot set property ‘financial’ of undefined

I have checked content of Chart.defaults and found that .elements is in ‘global’ so I changed

    225 const globalOpts = Chart.defaults.global
    316 const globalOpts$1 = Chart.defaults.global
    401 const globalOpts$2 = Chart.defaults.global

And eventually Error

    Chart.defaults.set(‘ohlc’ ... 

on line 446

So I changed them to:

    446 Chart.defaults.ohlc.datasets.barPercentage = 1.0,
    447 Chart.defaults.ohlc.datasets.categoryPercentage = 1.0

Then I got 

    UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at CandlestickController.draw (C:\inetpub\github\telegram-stream-trades\chartjs-chart-financial.js:213:32)

So I chagned:

    213 const rects = me.getMeta();

That handled all the errors. But still no candles drawn.

So probably the way I initially started is incorrect
