### ISSUE TITLE
Plugins from other npm modules

### ISSUE THREAD

**Issue by Perlkonig** [SeanSobey/ChartjsNodeCanvas#44]
I'm sorry to use the issues for a simple question. I'm trying to incorporate the [`chartjs-chart-box-and-violin-plot` plugin](https://github.com/datavisyn/chartjs-chart-box-and-violin-plot) in my server-side rendering app. I can't seem to figure out the magical incantation to get the plugin to register properly. An example would be extremely helpful.

Thanks for your time, and a very useful module!

**Comment by SeanSobey** [comment]
Hi,

Looking at the [source](https://unpkg.com/chartjs-chart-box-and-violin-plot@2.3.0/build/Chart.BoxPlot.js) for that lib the chart.js factory function approach should work:

```js
const chartJsFactory = () => {
    const chartJS = require('chart.js');
    require('chartjs-chart-box-and-violin-plot');
    delete require.cache[require.resolve('chart.js')];
    delete require.cache[require.resolve('chartjs-chart-box-and-violin-plot')];
    return chartJS;
};
const canvasRenderService = new CanvasRenderService(width, height, undefined, undefined, chartJsFactory);
```

There are [examples](https://github.com/SeanSobey/ChartjsNodeCanvas#older-plugins) of other methods if that does not work.

**Comment by Perlkonig** [comment]
Thanks for your time, Sean. It appears to be loading now. I'm having some other issues, but I need to do some more digging to isolate the cause. Thanks again.
