### ISSUE TITLE
How to activate ChartJS plugins?

### ISSUE THREAD

**Issue by vzhilov** [SeanSobey/ChartjsNodeCanvas#46]
Hello! You app is great and simplify a lot of things. Thank you for your work! 

However I can’t figure out how plugin activation work. I would like to use official datalabels plugin for ChartJs, but I can’t see any labels. Here is my code:

    `const Chart = require('chart.js');
    **const datalabels = require('chartjs-plugin-datalabels')**
    const { CanvasRenderService } = require('chartjs-node-canvas');

    const width = 600;
    const height = 400;
    const chartCallback = (ChartJS) => {

    ChartJS.defaults.global.elements.rectangle.borderWidth = 2;
    **ChartJS.plugins.register({
        datalabels
        });
    };**

    const canvasRenderService = new CanvasRenderService(width, height, chartCallback);

    (async () => {
    const configuration = {
        type: 'bar',
        data: {
            datasets: [
                {
                    type:"bar",
                    barThickness: 24,
                    label: 'My dataset',
                    data: ydata['data'],
                    backgroundColor: 'rgba(75,192, 192, 0.2)',
                    borderColor: 'rgba(54, 162, 135, 0.2)',
                    borderWidth: 1,
                    **datalabels: {
                        align: 'start',
                        anchor: 'start'
                    }**
                }, 
                labels: xdata,
            }

        options: {
            scales: {
                yAxes: [
                    {
                        id: 'left-y-axis',
                        position: 'left',
                        stacked: false,
                        ticks: {
                            beginAtZero: true,
                            callback: (value) => value + "R"
                        },
                    },
                    {
                        id: 'right-y-axis',
                        position: 'right'
                    }
                ],
                xAxes: [{
                    stacked: true,

                }]
            },
            plugins: {
                **datalabels: {
                    backgroundColor: function(context) {
                        return context.dataset.backgroundColor;
                    },
                    borderRadius: 4,
                    color: 'red',
                    font: {
                        weight: 'bold'
                    },
                    formatter: Math.round
                }
              }**
         }
    };
    const image = await canvasRenderService.renderToBuffer(configuration);
    fs.writeFileSync(tgMsgPath+"test.png", image)        
    })(); `

**Comment by SeanSobey** [comment]
Hi,

Please see [this](https://github.com/SeanSobey/ChartjsNodeCanvas/issues/37) issue
