### ISSUE TITLE
Grey instead of color

### ISSUE THREAD

**Issue by wh33ler** [SeanSobey/ChartjsNodeCanvas#48]
I am using this package in an AWS lambda environment and have issues with showing color. The colours are grey for some reason. Locally the colours are rendered fine. Also when using a [docker lambda environment](https://github.com/lambci/docker-lambda) the colours are shown. Only in an AWS environment the color reduces back to grey.

<img width="728" alt="Bildschirmfoto 2020-08-19 um 16 33 23" src="https://user-images.githubusercontent.com/815608/90648391-be2f3700-e239-11ea-9610-ea6030a21088.png">

I am using the layer [canvas-lib64-layer.zip](https://github.com/jwerre/node-canvas-lambda) 
and the following script to render the chart.

```
var Module = require('module')

const { CanvasRenderService } = require('chartjs-node-canvas');
const { CanvasRenderingContext2D, CanvasPattern, CanvasGradient } = require("canvas");

let schemesPlugin = undefined;

exports.handler = async (event) => {
    const width = event.width;
    const height = event.height;
    const canvasRenderService = new CanvasRenderService(width, height, (ChartJS) => {   

        ChartJS.defaults.global.defaultFontFamily = 'Arial';    
        ChartJS.defaults.global.elements.rectangle.borderWidth = 2;           
                
        global.CanvasRenderingContext2D = CanvasRenderingContext2D;
        global.CanvasPattern = CanvasPattern;
        global.CanvasGradient = CanvasGradient;          

        global.Chart = ChartJS;        
        require('chartjs-plugin-labels');
        
        schemesPlugin = require('./chartjs-plugin-colorschemes-mod');
        ChartJS.plugins.register(schemesPlugin);                
    });
    try{        
        canvasRenderService.registerFont('./arial.ttf', { family: 'Arial' });        
        let data = await canvasRenderService.renderToDataURL(event.chart);   
        return data;
    }catch(e) {
        console.log('Received event:', JSON.stringify(event, null, 2));
        console.log("Error", e);        
    }
};

```
And an example event with the configuration. This is not the same chart as shown above but the color issues are the same.
```
{
    "width": 700,
    "height": 400,
    "chart": {
        "type": "radar",
        "data": {
            "labels": [
                "Vehicles",
                "Accessories",
                "Digital",
                "Insurance"
            ],
            "datasets": [
                {
                    "label": "Revenue",
                    "data": [
                        900000,
                        700000,
                        600000,
                        750000
                    ],
                    "fill": false,
                    "lineTension": 0
                },
                {
                    "label": "Return",
                    "data": [
                        500000,
                        300000,
                        800000,
                        400000
                    ],
                    "fill": false,
                    "lineTension": 0
                }
            ]
        },
        "options": {       
            "maintainAspectRatio": true,
            "title": {
                "text": "The super title",
                "display": true
            },
            "plugins": {
                "colorschemes": {
                    "scheme": "brewer.Paired12"                    
                },
                "labels": {
                    "render": "value",
                    "position": "outside"
                }
            }            
        }
    }
}
```
Any ideas or hints are welcome. I have no idea where to start looking, because I cannot reproduce it locally and not in docker.
Thanks

**Comment by LukasHromadnik** [comment]
Do you have any update on this? I'm getting a gray bar chart on my laptop and have no idea what might be the problem.

**Comment by wh33ler** [comment]
No update yet, sorry. I get color on my dev machine but grey in the lambda environment. But I also don't have any clue where to look yet. In case you find something please be so kind and keep me in the loop. I will do too.

**Comment by SeanSobey** [comment]
Hi

Did you follow the [install instructions](https://github.com/Automattic/node-canvas/wiki/Installation%3A-AWS-Lambda) for AWS Lambda?

**Comment by wh33ler** [comment]
Hi,

I double checked it and I am not missing any crucial steps. I am using node12 instead, but I am doing mostly the same. Installing in docker copying the libs out and using them as layer in lambda. Not sure what could go wrong.

**Comment by wh33ler** [comment]
After doing some tests with multiple charts in a row I could see that every once in a while a chart gets rendered with color, but most of the time in grey. So it looks like a timing issue of some sort. The plugin I use `chartjs-plugin-colorschemes` uses the `beforeUpdate` event to set the colors of a chart. Could this maybe the source of the issue?

**Comment by wh33ler** [comment]
@SeanSobey  & @LukasHromadnik 
I figured it out. In my case it was an issue with the `chartjs-plugin-colorschemes` plugin. After implementing the logic in a simplified manner myself everything seemed to work. I am not sure what exactly causes the plugin not function properly though.
