### ISSUE TITLE
Getting boxes in place of text

### ISSUE THREAD

**Issue by thewebsitedev** [SeanSobey/ChartjsNodeCanvas#5]
Hello,

Thank you for this library.

I am trying to run it on my server (ubuntu 18.04) using latest nodejs but the chart is displaying boxes in place of text. Is it font related issue? I am using default English language.

Chart renders fine on my local server running on MacOS.

<img width="1124" alt="screenshot 2018-12-19 at 11 57 50 pm" src="https://user-images.githubusercontent.com/4481867/50240270-554f4600-03ea-11e9-8631-7d2ca8c03365.png">

**Comment by thewebsitedev** [comment]
Never mind the dependencies were missing. Fixed it by running this command for ubuntu:

`sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev`

Complete list for different OS mentioned [here](https://github.com/Automattic/node-canvas/#compiling).

**Comment by htke1** [comment]
> Never mind the dependencies were missing. Fixed it by running this command for ubuntu:
> 
> `sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev`
> 
> Complete list for different OS mentioned [here](https://github.com/Automattic/node-canvas/#compiling).

@thewebsitedev My function is in azure server, is there any dependency specially for it, it's os is Window in kudu and how to install the dependency
