### ISSUE TITLE
Image overflow when tried to scaled

### ISSUE THREAD

**Issue by DVGY** [SeanSobey/ChartjsNodeCanvas#50]
[Code](https://codesandbox.io/s/image-overflow-qxpfg?file=/src/index.js)

So I always want a good image, which I can zoom and see the content clearly. I tried to use the scale option, but it make the images zoomed and overflows it. 

Am I missing something ??

Note: **without scaling the code works fine, but I want an image that I can zoom and see clearly**

Thanks

**Comment by SeanSobey** [comment]
Don't use scale on the chart, rather set a large canvas size, see this issue: https://github.com/SeanSobey/ChartjsNodeCanvas/issues/32
