### ISSUE TITLE
Upgrade to 3.0.8 broke the app

### ISSUE THREAD

**Issue by vzhilov** [SeanSobey/ChartjsNodeCanvas#59]
After upgrading from 3.0.6 to 3.0.8 I got:

> TypeError: CanvasRenderService is not a constructor

So I had to change:

    const { CanvasRenderService } = require('chartjs-node-canvas');
    const canvasRenderService = new CanvasRenderService(width, height, undefined, undefined, chartJsFactory);

to

    const { ChartJSNodeCanvas } = require('chartjs-node-canvas');
    const canvasRenderService = new ChartJSNodeCanvas(width, height, undefined, undefined, chartJsFactory);

Then I got the following error:

> (node:9724) UnhandledPromiseRejectionWarning: Error: the surface type is not appropriate for the operation
>     at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
>     at processPromiseRejections (internal/process/promises.js:247:11)
>     at processTicksAndRejections (internal/process/task_queues.js:94:32)
> (node:9724) Error: the surface type is not appropriate for the operation
> (node:9724) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>     at emitDeprecationWarning (internal/process/promises.js:180:11)
>     at processPromiseRejections (internal/process/promises.js:249:13)
>     at processTicksAndRejections (internal/process/task_queues.js:94:32)

Should I adjust my code for the new version?

    const width = 600;
    const height = 400;

    const chartJsFactory = () => {
        require('chartjs-plugin-datalabels');
        delete require.cache[require.resolve('chart.js')];
        delete require.cache[require.resolve('chartjs-plugin-datalabels')];
        return Chart;
    }

    const canvasRenderService = new ChartJSNodeCanvas(width, height, undefined, undefined, chartJsFactory);

**Comment by project-curiosity** [comment]
I just started using this today so I don't know exactly what I am talking about. I ran into the same problem but by ramming my head at it and looking through the source code I found that the way of passing options to the ChartJSNodeCanvas constructor has changed but the examples hadn't. 

The constructor looks like this now.
```js
constructor(options) {
    this._width = options.width;
    this._height = options.height;
    const canvas = freshRequire_1.freshRequire('canvas');
    this._createCanvas = canvas.createCanvas;
    this._registerFont = canvas.registerFont;
    this._type = options.type && options.type.toLowerCase();
    this._chartJs = this.initialize(options.plugins, options.chartCallback);
}
```

So This
```js
const canvasRenderService = new ChartJSNodeCanvas(width, height, undefined, undefined, chartJsFactory);
```
Should be
```js
const canvasRenderService = new ChartJSNodeCanvas({
    width: parseInt(width),
    height: parseInt(height),
    chartCallback: chartJsFactory
});
```
Doing that worked for me. I also found that parseInt() was needed for the height and width. Again I am new to chartjs and canvas but I believe that problem has to do with how canvas. Changing the constructor to this also fixed that problem for me.
```js
constructor(options) {
    this._width = parseInt(options.width);
    this._height = parseInt(options.height);
    const canvas = freshRequire_1.freshRequire('canvas');
    this._createCanvas = canvas.createCanvas;
    this._registerFont = canvas.registerFont;
    this._type = options.type && options.type.toLowerCase();
    this._chartJs = this.initialize(options.plugins, options.chartCallback);
}
```

**Comment by SeanSobey** [comment]
Apologies for the inconvenience, it looks like I missed some of the examples in the version 3 update. I pushed an update to the docs to hopefully rectify the examples, per @project-curiosity.

@vzhilov The error you see should have shown up in the V3 major bump, not the patch increment as mentioned but either way hopefully the docs and examples are consistent now.

**Comment by timothyallan** [comment]
FWIW, I also started getting all these breaking errors as well after going from 3.0.6 to 3.0.8
