### ISSUE TITLE
Gradients not working properly

### ISSUE THREAD

**Issue by Helixable** [SeanSobey/ChartjsNodeCanvas#63]
I'm running node.js 15.12.0 on a linux machine

I'm trying to get gradients to work but they are just showing up as black.

Does anyone else have issues with this?

Steps to reproduce: set `backGroundcolor` property to any kind of gradient.

**Comment by Sehlor** [comment]
Having the same issue, i don't know why but it comes out as black.

**Comment by SeanSobey** [comment]
How are you creating the gradient? It needs to be created from a live canvas context, eg this works for me:

```ts
	const configuration: ChartConfiguration = {
		type: 'bar',
		data: {
			labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
			datasets: [{
				label: '# of Votes',
				data: [12, 19, 3, 5, 2, 3],
				backgroundColor: (ctx) => {
					if (!ctx.chart || !ctx.chart.ctx || !ctx.chart.chartArea) {
						return; // throw?
					}
					const chartArea = ctx.chart.chartArea;
			 		const gradient = ctx.chart.ctx.createLinearGradient(0, chartArea.bottom, 0, chartArea.top);
					gradient.addColorStop(0, 'blue');
					gradient.addColorStop(0.5, 'yellow');
					gradient.addColorStop(1, 'red');
					return gradient;
				},
				borderColor: [
					'rgba(255,99,132,1)',
					'rgba(54, 162, 235, 1)',
					'rgba(255, 206, 86, 1)',
					'rgba(75, 192, 192, 1)',
					'rgba(153, 102, 255, 1)',
					'rgba(255, 159, 64, 1)'
				],
				borderWidth: 1
			}]
		},
		options: {
		}
	};
```

**Comment by dogyeong** [comment]
same issue for me.

my env
- OS: Windows 10 10.0.19042
- Node: 14.17.1
- npm: 6.14.13

chart configuration
```js
const config = {
      type: 'line',
      data: {
        labels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        datasets: [
          {
            data: [65, 68, 70, 88, 78, 68, 94, 17, 100, 34],
            borderColor: 'red',
            cubicInterpolationMode: 'monotone',
            tension: 0.4,
            pointRadius: 0,
            fill: 'start',
            borderWidth: 2,
            backgroundColor: (ctx) => {
              if (!ctx.chart || !ctx.chart.ctx || !ctx.chart.chartArea) {
                return;
              }
              const chartArea = ctx.chart.chartArea;
              const gradient = ctx.chart.ctx.createLinearGradient(
                0,
                chartArea.bottom,
                0,
                chartArea.top,
              );
              gradient.addColorStop(0, 'blue');
              gradient.addColorStop(0.5, 'yellow');
              gradient.addColorStop(1, 'red');
              return gradient;
            },
          },
        ],
      },
  // ... more options
};
```

result
![image](https://user-images.githubusercontent.com/40662323/124703348-1e4fca00-df2d-11eb-9ec4-e7750bb33fb3.png)

**Comment by dogyeong** [comment]
it works with chart.js@2.9.4

**Comment by SeanSobey** [comment]
Yes, ChartJS 3.x.x is not yet officially supported

**Comment by WeeJeWel** [comment]
> How are you creating the gradient? It needs to be created from a live canvas context, eg this works for me:
> 
> 	const configuration: ChartConfiguration = {
> 		type: 'bar',
> 		data: {
> 			labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
> 			datasets: [{
> 				label: '# of Votes',
> 				data: [12, 19, 3, 5, 2, 3],
> 				backgroundColor: (ctx) => {
> 					if (!ctx.chart || !ctx.chart.ctx || !ctx.chart.chartArea) {
> 						return;
> 					}
> 					const chartArea = ctx.chart.chartArea;
> 			 		const gradient = ctx.chart.ctx.createLinearGradient(0, chartArea.bottom, 0, chartArea.top);
> 					gradient.addColorStop(0, 'blue');
> 					gradient.addColorStop(0.5, 'yellow');
> 					gradient.addColorStop(1, 'red');
> 					return gradient;
> 				},
> 				borderColor: [
> 					'rgba(255,99,132,1)',
> 					'rgba(54, 162, 235, 1)',
> 					'rgba(255, 206, 86, 1)',
> 					'rgba(75, 192, 192, 1)',
> 					'rgba(153, 102, 255, 1)',
> 					'rgba(255, 159, 64, 1)'
> 				],
> 				borderWidth: 1
> 			}]
> 		},
> 		options: {
> 		}
> 	};

@SeanSobey This seems to be working in `chart.js@^2.9.4` with `chartjs-node-canvas@^3.2.0`, but is broken in `chart.js@^3.9.1` & `chartjs-node-canvas@^4.1.6`. The background gradient does not render at all.
