### ISSUE TITLE
Will this work with serverless ?

### ISSUE THREAD

**Issue by crapthings** [SeanSobey/ChartjsNodeCanvas#66]
it returns "error: Transferred a partial file" if i send buffer api.

and return a empty png if i use stream api

but both api work with my osx while dev, but not serverless

```
const express = require('express')
const bodyParser = require('body-parser')
const cors = require('cors')
const { ChartJSNodeCanvas } = require('chartjs-node-canvas')

const {
  LIMIT = 1,
  PORT = 8080,
} = process.env

const server = express()

server.use(cors())
server.use(bodyParser.urlencoded({ extended: true, limit: `${LIMIT}mb` }))
server.use(bodyParser.json({ limit: `${LIMIT}mb` }))

;(async function () {
  server.post('/', function (req, res) {
    res.setHeader('content-type', 'image/png')
    try {
      const { width = 640, height = 480 } = req.body
      const chartJSNodeCanvas = new ChartJSNodeCanvas({ width, height })
      const stream = chartJSNodeCanvas.renderToStream(req.body)
      stream.on('data', function (data) {
        res.write(data)
      })
      stream.on('end', function () {
        res.end()
      })

      // chartJSNodeCanvas.renderToBuffer(req.body).then(resp => res.send(resp))
    } catch (ex) {
      console.log(ex)
      res.status(500).send('failed to render')
    }
  })

  server.listen(PORT, function () {
    console.log('Server is listening', PORT)
  })
})()

module.exports = server
```

![image](https://user-images.githubusercontent.com/1147704/116642155-c59a0900-a9a0-11eb-8f11-50fb33728550.png)

**Comment by SeanSobey** [comment]
Hi

Your code seems like it should work, have you looked at the install docs for [canvas on AWS](https://github.com/Automattic/node-canvas/wiki/Installation:-AWS-Lambda)? Assuming by serverless you mean AWS Lambda.

Is that screenshot of your local working version? Looks like you have the binary data there.

You can look at the [integration tests](https://github.com/SeanSobey/ChartjsNodeCanvas/blob/master/src/index.new.e2e.spec.ts) for examples of using buffers and streams.

FYI you can pipe streams:

```ts
stream.pipe(res);
```

Also note, in practice, you should not new up a `ChartJSNodeCanvas` instance for each server response but maintain one per required canvas width and height to avoid [GC and memory issues](https://github.com/SeanSobey/ChartjsNodeCanvas#memory-management).
