### ISSUE TITLE
ChartJS.plugins.register not working  with chartjs version 3.x

### ISSUE THREAD

**Issue by HoangMinh991** [SeanSobey/ChartjsNodeCanvas#67]
ChartJS.plugins.register not working  with chartjs 3.x version  , it only working with 2.x version
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'register' of undefined

**Comment by SeanSobey** [comment]
I have not yet looked at officially supporting `3.x.x` yet (hence the peer dependency of `^2.7.3`), but it seems like Aren's fix should work. Thanks for posting @Cartman720 ! I will look at trying to support v3 soon
