### ISSUE TITLE
canvas.getAttribute is not a function

### ISSUE THREAD

**Issue by vaasu070** [SeanSobey/ChartjsNodeCanvas#68]
I am using `npm 8.12.0`, `node-gyp 3.8.0 ` ,`chart.js 2.9.4` and `electron 6.12.0`

```

 const chartJSNodeCanvas = new ChartJSNodeCanvas({
    width: 500,
    height: 300
  });

  const configuration = {
    type: 'bar',
    data: {
      labels: ['a','b'],
      datasets: [
        { label: 'Error(%)', data:[]) }
      ]
    }
  };
  const image = chartJSNodeCanvas.renderToBufferSync(configuration);
```
The above code is giving this error. What does this mean?? Is this a bug??
![image](https://user-images.githubusercontent.com/33760706/117698787-b48f9a00-b1e1-11eb-81e3-fd48d1374dce.png)

**Comment by vaasu070** [comment]
Its working now.I moved this function to electron's main process.

**Comment by SeanSobey** [comment]
Thanks for posting your fix, I have not used this with Electron or aware of anyone using it before either, so good to know it works!
