### ISSUE TITLE
canvas background color

### ISSUE THREAD

**Issue by jan-bogaerts** [SeanSobey/ChartjsNodeCanvas#7]
Hi,
Looking into your lib. looks like a cool project. Got it working pretty fast.  I was wondering though, would it be possible to set some properties of the canvas element, so that you can, for instance, set the background color for the entire image?

**Comment by SeanSobey** [comment]
This is pretty easy to achieve with the ChartJS [Plugin API](https://www.chartjs.org/docs/latest/developers/plugins.html):

```js
const canvasRenderService = new CanvasRenderService(width, height, (ChartJS) => {
	ChartJS.plugins.register({
		beforeInit: (chart, options) => {
			const ctx = chart.ctx;
			ctx.fillStyle = '#FF0000';
			ctx.fillRect(0, 0, width, height);
		}
	});
});
const image = await canvasRenderService.renderToBuffer(configuration);
```

**Comment by jan-bogaerts** [comment]
Cool, thanks. Hadn't thought of that...

**Comment by jan-bogaerts** [comment]
by the way, had to use beforeDraw instead of beforeInit

**Comment by danbars** [comment]
For me this didn't work as is. 
1. I had to use `beforeDraw` as mentioned by @jan-bogaerts 
2. I had to save and restore context before and after painting the background.
```
beforeDraw: (chart, options) => {
        const ctx = chart.ctx;
        ctx.save();
        ctx.fillStyle = '#ffcccc';
        ctx.fillRect(0, 0, width, height);
        ctx.restore();
      }
```
