### ISSUE TITLE
Error running on AWS Lambda

### ISSUE THREAD

**Issue by guiphc** [SeanSobey/ChartjsNodeCanvas#75]
I got this error using a simple chart into node, running with serveless AWS.

please help :)

    "errorType": "Error",
    "errorMessage": "libuuid.so.1: cannot open shared object file: No such file or directory",
    "stack": [
        "Error: libuuid.so.1: cannot open shared object file: No such file or directory",
        "    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Module.require (internal/modules/cjs/loader.js:887:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at Object.<anonymous> (/var/task/node_modules/canvas/lib/bindings.js:3:18)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Module.require (internal/modules/cjs/loader.js:887:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at Object.<anonymous> (/var/task/node_modules/canvas/lib/canvas.js:9:18)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)"
    ]

**Comment by Jino-Thomas-HSPL** [comment]
https://github.com/Automattic/node-canvas/issues/1448#issuecomment-506529976

this solved the issue for me

**Comment by SeanSobey** [comment]
> 
> 
> [Automattic/node-canvas#1448 (comment)](https://github.com/Automattic/node-canvas/issues/1448#issuecomment-506529976)
> 
> this solved the issue for me

Thanks for posting your fix
