### ISSUE TITLE
Not able to register a new plugin

### ISSUE THREAD

**Issue by Remco-Muller** [SeanSobey/ChartjsNodeCanvas#77]
When i am trying to include 'chartjs-plugin-datalabels' it tells me 'Cannot read property 'register' of undefined'.

`var Chart = new ChartJSNodeCanvas({ width, height, plugins: {
      requireLegacy: ['chartjs-plugin-datalabels']
  } });`

Update:

The issue is in new.js at line 173. 
`chartJs.plugins.register(freshRequire_1.freshRequire(plugin));`

needs to be replace with
`chartJs.register(freshRequire_1.freshRequire(plugin));`

**Comment by SeanSobey** [comment]
What version of Chart JS are you using?

**Comment by Mw3y** [comment]
I'm using Chart.js 3.5.0 and I have the same error.
