### ISSUE TITLE
Cannot read property 'register' of undefined

### ISSUE THREAD

**Issue by adimberat** [SeanSobey/ChartjsNodeCanvas#78]
I always get this error.
![image](https://user-images.githubusercontent.com/61628863/125202132-e2916900-e27a-11eb-956f-b5d676fb4b0a.png)

![image](https://user-images.githubusercontent.com/61628863/125202143-e91fe080-e27a-11eb-9deb-b96bd06ed2ba.png)

**Comment by SeanSobey** [comment]
What version of chart JS are you using?

**Comment by Hoargarth** [comment]
Hey, got the same error when trying to register a plugin
`Cannot read property 'register' of undefined`

Using
ChartJS: v3.5.0
ChartjsNodeCanvas: v3.2.0
Node: 14.15.0 (also tried with Node 12)

**Comment by SeanSobey** [comment]
ChartJS 3.x.x is not yet officially supported

**Comment by Hoargarth** [comment]
Oh I see.
But for that it's already running pretty well
