### ISSUE TITLE
Cannot find namespace 'Chart'.

### ISSUE THREAD

**Issue by wooandoo** [SeanSobey/ChartjsNodeCanvas#84]
With Typescript 4.4.2, I have an error which is not present with TS 4.3.x:

node_modules/chartjs-node-canvas/dist/new.d.ts:8:46 - error TS2503: Cannot find namespace 'Chart'.

It seems that, in the file:
https://github.com/SeanSobey/ChartjsNodeCanvas/blob/c7267c8b73cc7281b926cad9c21c1ffe1afe9b53/src/new.ts
the "Chart" doesn't exist ("Chart as ChartJS" exists)

And I don't know what is "PluginServiceGlobalRegistration". I don't find it in the project chart.js

**Comment by tojurnru** [comment]
We're having the same issue as well, the temporary fix is to remove both namespace:
```
readonly modern?: ReadonlyArray<string>;
```

Of course this only works for local build but not CI. Any way to see a fix on this issue soon?

**Comment by tojurnru** [comment]
And we are running Typescript version 4.3.5

**Comment by SeanSobey** [comment]
Closing for now, if you have upgraded and experienced the same issue feel free to reopen.
