### ISSUE TITLE
Need help installing

### ISSUE THREAD

**Issue by MorningSleeper** [SeanSobey/ChartjsNodeCanvas#86]
Hi, trying to install and getting the following error which I do not understand how to resolve. Does it mean this package requires a version of chart.js < 3? Anyone know what I can try to get this installed with chart.js 3.5.1?

ubuntu@mail:/webserver/sites/bot$ sudo npm i chartjs-node-canvas chart.js
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: Bot@1.0.0
npm ERR! Found: chart.js@3.5.1
npm ERR! node_modules/chart.js
npm ERR!   chart.js@"^3.5.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer chart.js@"^2.7.3" from chartjs-node-canvas@3.2.0
npm ERR! node_modules/chartjs-node-canvas
npm ERR!   chartjs-node-canvas@"*" from the root project
```

**Comment by SeanSobey** [comment]
ChartJS V3 is not officially supported yet, but I am close to releasing an update

**Comment by MorningSleeper** [comment]
Ok, thanks for the reply, I will look forward to your release of the update.

**Comment by SeanSobey** [comment]
v4 is released and supports chart.js v3.x.x :)
