### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by bellus93** [SeanSobey/ChartjsNodeCanvas#89]
With this versions 
"chart.js": "^3.5.1",
"chartjs-node-canvas": "^4.0.1",    

"typescript": "4.4.4"

if i try to build my project I got this error 

node_modules/chartjs-node-canvas/dist/index.d.ts:1:23 - error TS2688: Cannot find type definition file for 'resemblejs'.

/// <reference types="resemblejs" />

**Comment by SeanSobey** [comment]
Thanks for reporting this. Very strange issue, the type definition for resemblejs (dev dependancy used only in tests) has a `declare global` that causes typescript to add  a `/// <reference types="resemblejs" />` to the main index file...weird. This is fixed and will be pushed up in the next release.
