### ISSUE TITLE
Image quality (2)

### ISSUE THREAD

**Issue by TimHav** [SeanSobey/ChartjsNodeCanvas#94]
**Describe the bug**
Be able to pass the render quality to the different render functions.

In [this similar issue](https://github.com/SeanSobey/ChartjsNodeCanvas/issues/32), the requestor was advised to scale up the canvas to get a higher resolution image. This works, but has as drawback that the texts in the graph are not scaled accordingly.

However, [node-canvas supports passing image quality as a parameter](https://github.com/Automattic/node-canvas#canvastobuffer), so this package can expose that in its API.

**Versions**
* NodeJS version: 16.13.0
* Chart.JS version: 3.6.0
* Typescript version: 4.4.4

**Comment by TimHav** [comment]
Another solution for this problem is to pass the `devicePixelRatio` as an option when generating an image. Do not set the `devicePixelRatio` higher when rendering on screen when you care about your animation performance.
https://www.chartjs.org/docs/latest/configuration/device-pixel-ratio.html

**Comment by SeanSobey** [comment]
It sounds like what you are after is increasing the [font size](https://www.chartjs.org/docs/latest/general/fonts.html), you should not need `devicePixelRatio` (and probably avoid it as it can cause other issues). Use canvas size to render the image at the resolution you plan to use, and increase the various font sizes as you need.

That said I am [adding support](https://github.com/SeanSobey/ChartjsNodeCanvas/tree/add-canvas-mime-config) for the mentioned APIs anyway. It may be useful for some applications but in most cases the defaults are fine.

**Comment by brandonsturgeon** [comment]
Is that branch dead? Seems like exactly what I'm looking for.

**Comment by samuelkilada** [comment]
@brandonsturgeon If you want to increase the quality, the above "devicePixelRatio" is the way to do it. Just do this in your "options" configuration (the same place where you put scales, etc.):

options: {
      devicePixelRatio: 2, // this doubles the default quality of 1
      scales: { ... }
}

I tried this out and the quality is so much better!
