### ISSUE TITLE
Unable to pass 2d array of data to bar chart for Range or Floating Bar Charts

### ISSUE THREAD

**Issue by saavy-eth** [SeanSobey/ChartjsNodeCanvas#97]
**Troubleshooting Checklist**
* You have a supported [Node JS version](https://github.com/SeanSobey/ChartjsNodeCanvas#node-js-version).
* You have a supported [Chart.JS version](https://github.com/SeanSobey/ChartjsNodeCanvas#chartsjs-version).
* If this is plugin related:
   - You have read the [plugin docs](https://github.com/SeanSobey/ChartjsNodeCanvas#loading-plugins).
   - You have read the chart.js [plugin docs](https://www.chartjs.org/docs/latest/developers/plugins.html).
   - You have searched for [similar plugin issues](https://github.com/SeanSobey/ChartjsNodeCanvas/issues?q=is%3Aissue+label%3Aplugin).
* If this is deployment/environment related:
   - You have read the [canvas docs](https://github.com/Automattic/node-canvas) and followed any environment specific steps.
   - You have searched for [similar deployment issues](https://github.com/SeanSobey/ChartjsNodeCanvas/issues?q=is%3Aissue+label%3Adeployment).

**Describe the bug**
When using just chartjs normally I am able to pass a 2D array of data to a bar chart and get a floating bar chart, however when using chartjsnodecanvas with TypeScript it says it's an invalid data type

**Versions**
* NodeJS version: 16.13.1
* Chart.JS version: 3.7.0
* Typescript version (if applicable): 4.5.5

**Additional context**
Here's a very short project that'll repro it

```import { ChartConfiguration } from "chart.js";
import { ChartJSNodeCanvas } from "chartjs-node-canvas";

async function buildChart() {
    const data: number[][] = [[0,5], [5, 20], [20, 60], [60, 100]];

    const ladder = new ChartJSNodeCanvas({height: 500, width: 500});

    const config: ChartConfiguration = {
        type: 'bar',
        data: {
            labels: ['0', '1', '2', '3'],
            datasets: [
                {
                    data
                }
            ]
        }
    }

    return await ladder.renderToDataURL(config)
}

console.log(buildChart);

**Comment by saavy-eth** [comment]
I have found a workaround with declaring data as an any[] and then just pushing arrays to it, but it's not ideal

**Comment by SeanSobey** [comment]
Hi there,

Sorry for the late reply. This is an issue with the chart.js typedocs, eg this lib just references the interfaces and API used by Chartjs:
```ts
import { ChartConfiguration } from 'chart.js';
```

Their ts docs are complicated and its most likely just an oversite, my suggestion would be to post a bug there. A not ideal but viable workaround while waiting could be to patch the [ts definition](https://www.chartjs.org/docs/latest/developers/charts.html#typescript-typings):
```ts
import { ChartTypeRegistry , ScatterDataPoint} from 'chart.js'

declare module 'chart.js' {
	interface ChartTypeRegistry {
		line: {
			defaultDataPoint: ScatterDataPoint | number | number[] | null;
		};
	}
}
```

**Comment by saavy-eth** [comment]
Hey Sean! Thank you for the reply and the thorough explanation. I'll bring this up with the team over at ChartJS

**Comment by jackmcpickle** [comment]
Yeah I have a similar issue when trying to use with a bar chart.
